enum Types {
  SEARCH_REQUEST = 'user/SEARCH_REQUEST',
  SEARCH_REQUEST_SUCCESS = 'user/SEARCH_REQUEST_SUCCESS',
  SEARCH_REQUEST_ERROR = 'user/SEARCH_REQUEST_ERROR',

  ERROR = 'user/ERROR',
}

export default Types
